Updated project files

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -89,12 +89,12 @@ jobs:
               rustup target add aarch64-unknown-linux-musl &&
               export OPENSSL_DIR=/usr &&
               yarn build --target aarch64-unknown-linux-musl
-#          - host: ubuntu-latest
-#            target: armv7-unknown-linux-gnueabihf
-#            setup: |
-#              sudo apt-get update
-#              sudo apt-get install gcc-arm-linux-gnueabihf -y
-#            build: yarn build --target armv7-unknown-linux-gnueabihf
+          #          - host: ubuntu-latest
+          #            target: armv7-unknown-linux-gnueabihf
+          #            setup: |
+          #              sudo apt-get update
+          #              sudo apt-get install gcc-arm-linux-gnueabihf -y
+          #            build: yarn build --target armv7-unknown-linux-gnueabihf
           - host: ubuntu-latest
             target: aarch64-linux-android
             build: yarn build --target aarch64-linux-android
@@ -154,52 +154,52 @@ jobs:
           name: bindings-${{ matrix.settings.target }}
           path: ${{ env.APP_NAME }}.*.node
           if-no-files-found: error
-#  build-freebsd:
-#    runs-on: ubuntu-latest
-#    name: Build FreeBSD
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Build
-#        id: build
-#        uses: cross-platform-actions/action@v0.25.0
-#        env:
-#          DEBUG: napi:*
-#          RUSTUP_IO_THREADS: 1
-#        with:
-#          operating_system: freebsd
-#          version: '14.0'
-#          memory: 8G
-#          cpu_count: 3
-#          environment_variables: 'DEBUG RUSTUP_IO_THREADS'
-#          shell: bash
-#          run: |
-#            sudo pkg install -y -f curl node libnghttp2 npm
-#            sudo npm install -g yarn --ignore-scripts
-#            curl https://sh.rustup.rs -sSf --output rustup.sh
-#            sh rustup.sh -y --profile minimal --default-toolchain beta
-#            source "$HOME/.cargo/env"
-#            echo "~~~~ rustc --version ~~~~"
-#            rustc --version
-#            echo "~~~~ node -v ~~~~"
-#            node -v
-#            echo "~~~~ yarn --version ~~~~"
-#            yarn --version
-#            pwd
-#            ls -lah
-#            whoami
-#            env
-#            freebsd-version
-#            yarn install
-#            yarn build
-#            rm -rf node_modules
-#            rm -rf target
-#            rm -rf .yarn/cache
-#      - name: Upload artifact
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: bindings-freebsd
-#          path: ${{ env.APP_NAME }}.*.node
-#          if-no-files-found: error
+  #  build-freebsd:
+  #    runs-on: ubuntu-latest
+  #    name: Build FreeBSD
+  #    steps:
+  #      - uses: actions/checkout@v4
+  #      - name: Build
+  #        id: build
+  #        uses: cross-platform-actions/action@v0.25.0
+  #        env:
+  #          DEBUG: napi:*
+  #          RUSTUP_IO_THREADS: 1
+  #        with:
+  #          operating_system: freebsd
+  #          version: '14.0'
+  #          memory: 8G
+  #          cpu_count: 3
+  #          environment_variables: 'DEBUG RUSTUP_IO_THREADS'
+  #          shell: bash
+  #          run: |
+  #            sudo pkg install -y -f curl node libnghttp2 npm
+  #            sudo npm install -g yarn --ignore-scripts
+  #            curl https://sh.rustup.rs -sSf --output rustup.sh
+  #            sh rustup.sh -y --profile minimal --default-toolchain beta
+  #            source "$HOME/.cargo/env"
+  #            echo "~~~~ rustc --version ~~~~"
+  #            rustc --version
+  #            echo "~~~~ node -v ~~~~"
+  #            node -v
+  #            echo "~~~~ yarn --version ~~~~"
+  #            yarn --version
+  #            pwd
+  #            ls -lah
+  #            whoami
+  #            env
+  #            freebsd-version
+  #            yarn install
+  #            yarn build
+  #            rm -rf node_modules
+  #            rm -rf target
+  #            rm -rf .yarn/cache
+  #      - name: Upload artifact
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: bindings-freebsd
+  #          path: ${{ env.APP_NAME }}.*.node
+  #          if-no-files-found: error
   test-macOS-windows-binding:
     name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
     needs:
@@ -376,56 +376,56 @@ jobs:
           run: |
             set -e
             yarn test
-#  test-linux-arm-gnueabihf-binding:
-#    name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
-#    needs:
-#      - build
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        node:
-#          - '18'
-#          - '20'
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Download artifacts
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: bindings-armv7-unknown-linux-gnueabihf
-#          path: .
-#      - name: List packages
-#        run: ls -R .
-#        shell: bash
-#      - name: Install dependencies
-#        run: |
-#          yarn config set supportedArchitectures.cpu "arm"
-#          yarn install
-#      - name: Set up QEMU
-#        uses: docker/setup-qemu-action@v3
-#        with:
-#          platforms: arm
-#      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-#      - name: Setup and run tests
-#        uses: addnab/docker-run-action@v3
-#        with:
-#          image: node:${{ matrix.node }}-bullseye-slim
-#          options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build'
-#          run: |
-#            set -e
-#            yarn test
-#            ls -la
+  #  test-linux-arm-gnueabihf-binding:
+  #    name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
+  #    needs:
+  #      - build
+  #    strategy:
+  #      fail-fast: false
+  #      matrix:
+  #        node:
+  #          - '18'
+  #          - '20'
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - uses: actions/checkout@v4
+  #      - name: Download artifacts
+  #        uses: actions/download-artifact@v4
+  #        with:
+  #          name: bindings-armv7-unknown-linux-gnueabihf
+  #          path: .
+  #      - name: List packages
+  #        run: ls -R .
+  #        shell: bash
+  #      - name: Install dependencies
+  #        run: |
+  #          yarn config set supportedArchitectures.cpu "arm"
+  #          yarn install
+  #      - name: Set up QEMU
+  #        uses: docker/setup-qemu-action@v3
+  #        with:
+  #          platforms: arm
+  #      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+  #      - name: Setup and run tests
+  #        uses: addnab/docker-run-action@v3
+  #        with:
+  #          image: node:${{ matrix.node }}-bullseye-slim
+  #          options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build'
+  #          run: |
+  #            set -e
+  #            yarn test
+  #            ls -la
   publish:
     name: Publish
     runs-on: ubuntu-latest
     needs:
-#      - build-freebsd
+      #      - build-freebsd
       - test-macOS-windows-binding
       - test-linux-x64-gnu-binding
       - test-linux-x64-musl-binding
       - test-linux-aarch64-gnu-binding
       - test-linux-aarch64-musl-binding
-#      - test-linux-arm-gnueabihf-binding
+    #      - test-linux-arm-gnueabihf-binding
     steps:
       - uses: actions/checkout@v4
       - name: Setup node
